### ISSUE TITLE
It Contain A Token Grabber Too

### ISSUE THREAD

**Issue by GAGOU78** [IND-PIYUSH/Selfbot#1]
i have deleted your webhook
and your selfbot its a fucking skid
fuck you

**Comment by IND-PIYUSH** [comment]
Bruh its not have any webhook and if you claiming you deleted that webhook give me that webhook you deleted

**Comment by IND-PIYUSH** [comment]
Bro First Calm Down And Tell Me Where Is The Webhook You Were Talking About

**Comment by IND-PIYUSH** [comment]
Bro You Were right Sry For That
wait let me remove it

**Comment by IND-PIYUSH** [comment]
I removed That Part You can use it Now And Thanks For Telling It Cause I am Using it too
